In [1]:
## Importing libraries

import pandas as pd
import numpy as np
import sys; sys.path.insert(1, '/Users/EvanCallaghan/Documents/Golf/StrokesGained/GOLF/GlobalScripts')
pd.set_option('display.max_rows', None, 'display.max_columns', None)
import sg_script as sg
import sg_script_editor as sg_editor

In [2]:
## Reading the data

baselines = pd.read_excel('/Users/EvanCallaghan/Documents/Golf/StrokesGained/Database/Baselines.xlsx')
courses = pd.read_excel('/Users/EvanCallaghan/Documents/Golf/StrokesGained/Database/Courses.xlsx')
golfers = pd.read_excel('/Users/EvanCallaghan/Documents/Golf/StrokesGained/Database/Golfers.xlsx')
rounds = pd.read_excel('/Users/EvanCallaghan/Documents/Golf/StrokesGained/Database/Rounds.xlsx')
shots = pd.read_excel('/Users/EvanCallaghan/Documents/Golf/StrokesGained/Database/Shots.xlsx')

## Individual round analysis:

In [3]:
## Subsetting the data for the correct golfer and round
golfer = golfers[golfers['Name'] == 'Evan Callaghan'].reset_index(drop = True)
rd = rounds[rounds['roundID'] == 1030].reset_index(drop = True)
shot = shots[shots['roundID'] == 1030].reset_index(drop = True)
course = courses[(courses['courseID'] == rd.at[0, 'courseID']) & (courses['Tees'] == rd.at[0, 'Tees'])].reset_index(drop = True)

## Creating complete data-frame for analysis
shotLevel, roundLevel = sg.initialize(shot, rd, course, baselines)

## Exporting data-frames for analysis:
shotLevel.to_csv('/Users/EvanCallaghan/Documents/Golf/StrokesGained/Reporting/shotLevel.csv', index = False)
roundLevel.to_csv('/Users/EvanCallaghan/Documents/Golf/StrokesGained/Reporting/roundLevel.csv', index = False)
courses.to_csv('/Users/EvanCallaghan/Documents/Golf/StrokesGained/Reporting/courseLevel.csv', index = False)

In [21]:
## Subsetting the data for the correct golfer and rounds

## Golfer
golfer = golfers[golfers['Name'] == 'Evan Callaghan'].reset_index(drop = True)

## Rounds
rds = rounds[(rounds['Name'] == 'Evan Callaghan') & (rounds['roundID'] >= 1030)].reset_index(drop = True)

## Shots
rds_unique = rds['roundID'].unique()
shot = shots[np.isin(shots['roundID'], rds_unique)].reset_index(drop = True)

## Course
course = courses[(courses['courseID'] == rounds.at[0, 'courseID']) & (courses['Tees'] == rounds.at[0, 'Tees'])].reset_index(drop = True)

# ## Creating complete data-frame for analysis
# shotLevel, roundLevel = sg.initialize(shot, rds, courses, baselines)

In [16]:
np.isin(shots['roundID'], rds_unique)

array([False, False, False, ..., False, False, False])

In [11]:
rds['roundID'].unique()

array([1030, 1032, 1038])

In [13]:
np.isin(rds['roundID'].unique(), [1030])

array([ True, False, False])

In [ ]:
## Exporting data-frames for analysis:

shotLevel.to_csv('/Users/EvanCallaghan/Documents/Golf/StrokesGained/Reporting/shotLevel.csv', index = False)
roundLevel.to_csv('/Users/EvanCallaghan/Documents/Golf/StrokesGained/Reporting/roundLevel.csv', index = False)
courses.to_csv('/Users/EvanCallaghan/Documents/Golf/StrokesGained/Reporting/courseLevel.csv', index = False)